### ISSUE TITLE
Occasional CVODES failure on OSX in BirthDeath example

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/LNAplusplus#17]
Works on Ubuntu, fails on OSX:
```
[CVODES ERROR]  CVode
  At t = 1.51964e-13, mxstep steps taken before reaching tout.
SUNDIALS_ERROR: CVodefailed with flag = -1
Traceback (most recent call last):
  File "models/BirthDeath.py", line 221, in <module>
    MRE, Var, Sens_MRE, Sens_Var,Sens2_MRE,Sens2_Var = BirthDeathLNA.LNA(Theta, tspan, Y0=MRE0, V0=Var0, merr=VarNoise, obsVar=ObsIndex, computeSens2=True)
BirthDeath.error: Error encountered during computation.
```
See https://travis-ci.org/ICB-DCM/LNAplusplus/jobs/369133949

**Comment by JanHasenauer** [comment]
hm, works for the matlab branch

**Comment by dweindl** [comment]
Okay, apparently this is not reproducible. The subsequent build worked:
https://travis-ci.org/ICB-DCM/LNAplusplus/jobs/369134440

**Comment by dweindl** [comment]
May also occur with 1st-order sensitiivities:
```
[CVODES ERROR]  CVode
  At t = 0 and h = 2.0825e-16, the corrector convergence test failed repeatedly or with |h| = hmin.
SUNDIALS_ERROR: CVodefailed with flag = -4
Traceback (most recent call last):
  File "models/BirthDeath.py", line 197, in <module>
    MRE, Var, Sens_MRE, Sens_Var = BirthDeathLNA.LNA(Theta, tspan, Y0=MRE0, V0=Var0, merr=VarNoise, obsVar=ObsIndex, computeSens=True)
BirthDeath.error: Error encountered during computation.
```
https://travis-ci.org/ICB-DCM/LNAplusplus/jobs/369151965

**Comment by JanHasenauer** [comment]
strange. the whole thing should be deterministic.

**Comment by dweindl** [comment]
Can't find anything suspicious when checking with valgrind (on Ubuntu). Not sure what is wrong there. So far only happened on OSX.

**Comment by JanHasenauer** [comment]
I tested it now on my mac under python. everything was running without an issue.

**Comment by dweindl** [comment]
This is pretty random. Happens with both clang and gcc, but only on osx. Should try different xcode or osx versions to narrow it down. @JanHasenauer  Which versions are you using?
